<link rel='dns-prefetch' href='//cybertronics.org.in' />
<link rel='dns-prefetch' href='//itunes.apple.com' />
<link rel='dns-prefetch' href='//youtube.com' />
<link rel='dns-prefetch' href='//imdb.com' />
<link rel='dns-prefetch' href='//en.wikipedia.org' />
<link rel='dns-prefetch' href='//facebook.com' />
<link rel='dns-prefetch' href='//twitter.com' />
<link rel='dns-prefetch' href='//reddit.com' />
<link rel='dns-prefetch' href='//linkedin.com' />
